[package]
name = "simhls"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "simhls"
path = "src/main.rs"

[dependencies]
rocket="0.5.1"
rocket_cors ="0.6.0"
tokio="1.43.0"
serde="1.0.217"
serde_json="1.0.137"

